// Raw riddle data - authentic Turkish bilmeceler
// Format: [question, answer, emoji, category, ageGroup, difficulty, hint]
module.exports = [
    // === 4-6 YAŞ - KOLAY (hayvanlar) ===
    ["Damda gezer, miyav der, süt içer.", "Kedi", "🐱", "hayvanlar", "4-6", "kolay", "Evde beslenen tüylü hayvan"],
    ["Hav hav der, kuyruk sallar, evi bekler.", "Köpek", "🐶", "hayvanlar", "4-6", "kolay", "İnsanın en iyi dostu"],
    ["Çalı dibinde fişek, bunu bilmeyen eşek.", "Tavşan", "🐰", "hayvanlar", "4-6", "kolay", "Havuç sever, zıplar"],
    ["Kümeslerin efesi, her sabah çınlar sesi.", "Horoz", "🐓", "hayvanlar", "4-6", "kolay", "Sabahları öter"],
    ["Elemeden yoğurur, gün aşırı doğurur.", "Tavuk", "🐔", "hayvanlar", "4-6", "kolay", "Yumurta yapar"],
    ["Yer altında yağlı kayış.", "Yılan", "🐍", "hayvanlar", "4-6", "kolay", "Sürünen uzun hayvan"],
    ["Tavan üstü takır takır, zannedersin halı dokur.", "Fare", "🐭", "hayvanlar", "4-6", "kolay", "Kedinin kovaladığı küçük hayvan"],
    ["Dağdan gelir sekerek, kara üzüm dökerek.", "Kuzu", "🐑", "hayvanlar", "4-6", "kolay", "Koyunun yavrusu"],
    ["Dalda durur, elde durmaz.", "Kuş", "🐦", "hayvanlar", "4-6", "kolay", "Gökyüzünde uçar"],
    ["Altından su içerim, üstünde çayır biçerim.", "Koyun", "🐑", "hayvanlar", "4-6", "kolay", "Yünlü hayvan"],
    ["Karşıdan baktım hiç yok, yanına vardım pek çok.", "Karınca", "🐜", "hayvanlar", "4-6", "kolay", "Çok küçük, çok çalışkan"],
    ["Karşıdan gördüm bir taş, yanına vardım dört ayak bir baş.", "Kaplumbağa", "🐢", "hayvanlar", "4-6", "kolay", "Evi sırtında taşır"],
    ["Kanadı var kuş değil, boynuzu var koç değil.", "Kelebek", "🦋", "hayvanlar", "4-6", "kolay", "Çiçekten çiçeğe konar"],
    ["Dağ başında kara papak.", "Keçi", "🐐", "hayvanlar", "4-6", "kolay", "Dağlarda yaşar, sakalı var"],
    ["Yer altında yuvası var, fırça gibi dikeni var.", "Kirpi", "🦔", "hayvanlar", "4-6", "kolay", "Dikenli minik hayvan"],
    ["Ay varken uçar, gün varken kaçar.", "Yarasa", "🦇", "hayvanlar", "4-6", "kolay", "Gece uçan hayvan"],
    // === 4-6 YAŞ - KOLAY (yiyecek) ===
    ["Çarşıdan aldım bir tane, eve geldim bin tane.", "Nar", "🍎", "yiyecek", "4-6", "kolay", "İçi taneli kırmızı meyve"],
    ["Dal üstünde al yanak, inanmazsan ye de bak.", "Elma", "🍎", "yiyecek", "4-6", "kolay", "Kırmızı veya yeşil meyve"],
    ["Bir sapı var yüz topu var.", "Üzüm", "🍇", "yiyecek", "4-6", "kolay", "Salkım şeklinde meyve"],
    ["Alçacık dallı, yemesi ballı.", "Çilek", "🍓", "yiyecek", "4-6", "kolay", "Küçük kırmızı meyve"],
    ["Yeşil montlu, kırmızı elbiseli, kahverengi düğmeli.", "Karpuz", "🍉", "yiyecek", "4-6", "kolay", "Yazın yenen büyük meyve"],
    ["Dereler tepeler, şık şık küpeler.", "Kiraz", "🍒", "yiyecek", "4-6", "kolay", "İkiz meyve"],
    ["Bir küçücük fıçıcık, içi dolu turşucuk.", "Limon", "🍋", "yiyecek", "4-6", "kolay", "Ekşi sarı meyve"],
    ["Yer altında sakallı dede.", "Soğan", "🧅", "yiyecek", "4-6", "kolay", "Soyunca ağlatır"],
    ["Yol üstünde kırmızı bohça.", "Domates", "🍅", "yiyecek", "4-6", "kolay", "Salatalara konur, kırmızıdır"],
    ["Kat kat döşek, bunu bilmeyen eşek.", "Lahana", "🥬", "yiyecek", "4-6", "kolay", "Yaprak yaprak sebze"],
    // === 4-6 YAŞ - KOLAY (doğa) ===
    ["Gökte durur paslanmaz, suya düşer ıslanmaz.", "Güneş", "☀️", "doğa", "4-6", "kolay", "Gündüz parlayan"],
    ["Akşam baktım çok idi, sabah baktım yok idi.", "Yıldız", "⭐", "doğa", "4-6", "kolay", "Gece gökyüzünde parlar"],
    ["Gökte gördüm bir köprü, rengi yedi türlü.", "Gökkuşağı", "🌈", "doğa", "4-6", "kolay", "Yağmurdan sonra çıkar"],
    ["Yol üstünde yarım börek.", "Ay", "🌙", "doğa", "4-6", "kolay", "Gece parlayan"],
    ["Ayağımla basınca kırt kırt eder, güneşi görünce eriyip gider.", "Kar", "❄️", "doğa", "4-6", "kolay", "Kışın yağar, beyazdır"],
    ["Bulutlardan süzülür, inci gibi dizilir.", "Yağmur", "🌧️", "doğa", "4-6", "kolay", "Bulutlardan düşer"],
    ["Ben giderim o gider, kah benden önce gider.", "Gölge", "👤", "doğa", "4-6", "kolay", "Güneşte arkanda durur"],
    // === 4-6 YAŞ - KOLAY (eşyalar) ===
    ["Dışı var içi yok, tekme yer suçu yok.", "Top", "⚽", "eşyalar", "4-6", "kolay", "Parkta onunla oynarsın"],
    ["Alçacık çınar, tutuşmuş yanar.", "Mum", "🕯️", "eşyalar", "4-6", "kolay", "Doğum gününde üflenir"],
    ["Kabuğu var içi yok, sopa yer suçu yok.", "Davul", "🥁", "eşyalar", "4-6", "kolay", "Vurarak ses çıkarırsın"],
    ["Bilgi verir herkese, en güzel dosttur bize.", "Kitap", "📖", "eşyalar", "4-6", "kolay", "Sayfaları vardır, okursun"],
    ["Ne kanı var ne canı, beş tanedir parmağı.", "Eldiven", "🧤", "eşyalar", "4-6", "kolay", "Kışın ellerine giyer"],
    ["Yarım kaşık duvara yapışık.", "Kulak", "👂", "vücut", "4-6", "kolay", "Onunla duyarsın"],
    ["Dişim var ağzım yok.", "Tarak", "🪥", "eşyalar", "4-6", "kolay", "Saçını onunla tararsın"],
    ["Bir sihirli fenerim, kibritsiz de yanarım.", "Ampul", "💡", "eşyalar", "4-6", "kolay", "Karanlıkta ışık verir"],
    // === 4-6 YAŞ - ORTA ===
    ["Gelişi aslan gibi, duruşu kaplan gibi, yayılır hasır gibi.", "Kedi", "🐱", "hayvanlar", "4-6", "orta", "Evde yaşayan tüylü hayvan"],
    ["Pamuk gibi tüyleri, havucu koparır dişleri.", "Tavşan", "🐰", "hayvanlar", "4-6", "orta", "Zıplayan beyaz hayvan"],
    ["Daldan dala kırmızı pala.", "Sincap", "🐿️", "hayvanlar", "4-6", "orta", "Fındık seven kuyruklu hayvan"],
    ["Arşın ayaklı burma bıyıklı.", "Tavşan", "🐰", "hayvanlar", "4-6", "orta", "Uzun kulaklı hayvan"],
    ["Çiçek onun, dal onun, yediğimiz bal onun.", "Arı", "🐝", "hayvanlar", "4-6", "orta", "Bal yapan böcek"],
    ["Benim bir hayvanım var, kuyruğundan uzun burnu var.", "Fil", "🐘", "hayvanlar", "4-6", "orta", "En büyük kara hayvanı"],
    ["Sırtında ev, karnında yol.", "Salyangoz", "🐌", "hayvanlar", "4-6", "orta", "Çok yavaş giden"],
    ["İki kanadı var yüzer gölde, uçar gökte.", "Ördek", "🦆", "hayvanlar", "4-6", "orta", "Vak vak der"],
    ["Bir küçücük fıçım var, iki türlü su yutar.", "Yumurta", "🥚", "yiyecek", "4-6", "orta", "Tavuğun yaptığı"],
    ["Ak saray içinde sarı sultan.", "Yumurta", "🥚", "yiyecek", "4-6", "orta", "Kaynatıp yersin"],
    ["Uzun Ali uzanır, günde uşak kazanır.", "Salatalık", "🥒", "yiyecek", "4-6", "orta", "Yeşil uzun sebze"],
    ["Hanım içerde, saçı dışarıda.", "Mısır", "🌽", "yiyecek", "4-6", "orta", "Sarı taneli sebze"],
    ["Boyun uzun mu uzun, yavrular düzüm düzüm.", "Mısır", "🌽", "yiyecek", "4-6", "orta", "Kabuğunu soyarsın"],
    ["Allah yapar yapısını, bıçak açar kapısını.", "Karpuz", "🍉", "yiyecek", "4-6", "orta", "Yeşil dışı kırmızı içi"],
    ["Yer altında sakallı kök.", "Pırasa", "🥬", "yiyecek", "4-6", "orta", "Yeşil yapraklı sebze"],
    ["Ben giderim o gider, üstümde gölge eder.", "Şemsiye", "☂️", "eşyalar", "4-6", "orta", "Yağmurda başının üstüne tutarsın"],
    ["O içinde, oda onun içinde.", "Ayna", "🪞", "eşyalar", "4-6", "orta", "Kendini onda görürsün"],
    ["Alınca elimize, alo deriz herkese.", "Telefon", "📱", "eşyalar", "4-6", "orta", "Konuşmak için kullanırsın"],
    ["Çocukların yuvası, bilgi doludur orası.", "Okul", "🏫", "eşyalar", "4-6", "orta", "Her gün oraya gidersin"],
    ["İki kapağım var, bir sürü yaprağım; ne ağacım, ne çiçeğim.", "Kitap", "📖", "eşyalar", "4-6", "orta", "Okuyarak öğrenirsin"],
    // === 4-6 YAŞ - ZOR ===
    ["Kendi çalışır ele, konar çiçeğe güle.", "Arı", "🐝", "hayvanlar", "4-6", "zor", "İğnesi var, bal yapar"],
    ["Eti haram sütü helal, canı var kanı yok.", "Arı", "🐝", "hayvanlar", "4-6", "zor", "Küçük uçan böcek"],
    ["Tüylü tüylü herkes onu çok sever, dikkat et çifte atarsa üzülürsün.", "At", "🐴", "hayvanlar", "4-6", "zor", "Üstüne binilir"],
    ["Gökten yağar kar değil, ses çıkarır taş değil.", "Dolu", "🧊", "doğa", "4-6", "zor", "Buz taneleri yağar"],
    ["Bir yorganım var, toprağı tutar denizi tutmaz.", "Kar", "❄️", "doğa", "4-6", "zor", "Beyaz örtü"],
    ["Avludan atladım, avlu üstüne yumurtladım.", "Kabak", "🎃", "yiyecek", "4-6", "zor", "Büyük turuncu sebze"],
    ["Gündüz asılı, gece basılı.", "Kilit", "🔒", "eşyalar", "4-6", "zor", "Kapıya takılır"],
    ["Dağdan gelir hop hop, ayağında sulu top.", "Kar", "❄️", "doğa", "4-6", "zor", "Kışın yağar"],
    ["Çaldım çıktım, kapı arkasını attım.", "Süpürge", "🧹", "eşyalar", "4-6", "zor", "Yerleri temizler"],
    ["Takır takır takraba, içinde var akraba.", "Beşik", "🛏️", "eşyalar", "4-6", "zor", "Bebek onda uyur"],
    // === 7-9 YAŞ - KOLAY ===
    ["Üstü mermer altı mermer, içinde gelin oynar.", "Dil", "👅", "vücut", "7-9", "kolay", "Ağzının içinde"],
    ["Bir tencerem var kapaklı, etrafı saçaklı.", "Göz", "👁️", "vücut", "7-9", "kolay", "Onunla görürsün"],
    ["İki yuvarlak, biri büyük biri küçük, onlar olmasa dünya kapkara.", "Göz", "👁️", "vücut", "7-9", "kolay", "Yüzünde iki tane var"],
    ["Alaca mezar dünyayı gezer.", "Göz", "👁️", "vücut", "7-9", "kolay", "Açıp kapatırsın"],
    ["Etten kantar, altın tartar.", "Kulak", "👂", "vücut", "7-9", "kolay", "Küpe takılır"],
    ["Kuyruğu var at değil, kanadı var kuş değil.", "Balık", "🐟", "hayvanlar", "7-9", "kolay", "Suda yaşar"],
    ["Demir üstünde teker, dünyayı gezer.", "Tren", "🚂", "araçlar", "7-9", "kolay", "Raylarda gider"],
    ["Direk üstünde teller, bize haber yollar.", "Telefon", "📱", "eşyalar", "7-9", "kolay", "Haberleşme aracı"],
    ["Bir sihirli sandığım var, içinde dünya var.", "Televizyon", "📺", "eşyalar", "7-9", "kolay", "Evde izlediğin cihaz"],
    ["Bir ağacı oymuşlar, içine dünyayı koymuşlar.", "Televizyon", "📺", "eşyalar", "7-9", "kolay", "Ekranında filmler oynar"],
    ["Ak akça karalar, birbirini kovalar.", "Dalgalar", "🌊", "doğa", "7-9", "kolay", "Denizde görürsün"],
    ["Benim bir ninem var, gece gündüz yufka açar.", "Dalga", "🌊", "doğa", "7-9", "kolay", "Sahilde kıyıya vurur"],
    ["Dört ayağı var canı yok, ayağını kessen kanı yok.", "Masa", "🪵", "eşyalar", "7-9", "kolay", "Üstünde yemek yersin"],
    ["Küçük küçük dişleri var, ne de büyük işleri var.", "Tarak", "🪥", "eşyalar", "7-9", "kolay", "Saçını düzeltir"],
    ["Kulağını büktükçe ağzı sulanır.", "Musluk", "🚰", "eşyalar", "7-9", "kolay", "Su akar ondan"],
    ["Kıştan kaçmaz, yaprağı uçmaz.", "Çam", "🌲", "doğa", "7-9", "kolay", "Her mevsim yeşil ağaç"],
    ["Çarşıdan aldım kapkara, evde kırmızılaştı maskara.", "Kömür", "⬛", "eşyalar", "7-9", "kolay", "Sobada yanar"],
    // === 7-9 YAŞ - ORTA ===
    ["Anası su babası taş, yedi aleme baş.", "Tuz", "🧂", "yiyecek", "7-9", "orta", "Yemeğe tat verir"],
    ["On iki oğlu dört kızı var.", "Yıl", "📅", "doğa", "7-9", "orta", "12 ayı var"],
    ["Bir ağacım var, on iki dalı, dört yaprağı, elli iki damarı var.", "Yıl", "📅", "doğa", "7-9", "orta", "Takvimde görürsün"],
    ["Üstünden ot biçilir, altından süt içilir.", "Koyun", "🐑", "hayvanlar", "7-9", "orta", "Çayırda otlar"],
    ["Gider Leylam gelir Leylam, tek ayak üstünde durur Leylam.", "Kapı", "🚪", "eşyalar", "7-9", "orta", "Açılır kapanır"],
    ["Aşağı iner tıkır tıkır, yukarı çıkar şıpır şıpır.", "Kova", "🪣", "eşyalar", "7-9", "orta", "Kuyudan su çeker"],
    ["Kat kattır katmer değil, kırmızıdır elma değil.", "Soğan", "🧅", "yiyecek", "7-9", "orta", "Soyunca ağlatır"],
    ["Çıt demeden çalıya geçti.", "Güneş ışığı", "☀️", "doğa", "7-9", "orta", "Sessiz gelir, her yere girer"],
    ["Ben giderim o kalır.", "Ayak izi", "👣", "vücut", "7-9", "orta", "Karda görürsün"],
    ["Yürürüm iz etmem, söylerim ses etmem.", "Saat", "🕐", "eşyalar", "7-9", "orta", "Zamanı gösterir"],
    ["İstanbul'da süt pişti, kokusu buraya düştü.", "Mektup", "✉️", "eşyalar", "7-9", "orta", "Postacı getirir"],
    ["Beyazdan akar çevreyi yıkar.", "Sel", "🌊", "doğa", "7-9", "orta", "Sular taşınca olur"],
    ["Altı taş üstü kül, içinde bir sarı gül.", "Ateş", "🔥", "doğa", "7-9", "orta", "Ocakta yanar"],
    ["Kışın yatar, yazın kalkar.", "Soba", "🏠", "eşyalar", "7-9", "orta", "Odayı ısıtır"],
    ["Uzaktan baktım bir çok, yanına gittim hiç yok.", "Sis", "🌫️", "doğa", "7-9", "orta", "Görüşü engeller"],
    ["Çıtırdamadan pıtırdamadan ormana gire.", "Güneş", "☀️", "doğa", "7-9", "orta", "Her gün doğar"],
    ["Dağdan gelir dura dura, hınzırları sile sile.", "Tarak", "🪥", "eşyalar", "7-9", "orta", "Saçtan geçer"],
    ["Elde yapılır, ete takılır.", "Yüzük", "💍", "eşyalar", "7-9", "orta", "Parmağa takılır"],
    ["Ağzı vardır konuşmaz, yatağı vardır uyumaz.", "Nehir", "🏞️", "doğa", "7-9", "orta", "Akar durur"],
    ["Ben varmadan o varır, her şeyden çok yol alır.", "Işık", "💡", "doğa", "7-9", "orta", "En hızlı şey"],
    ["İz eder dizi dizi, alır götürür bizi.", "Ayak", "🦶", "vücut", "7-9", "orta", "Yürüyorsun onlarla"],
    ["Ayakta yetişen bitki nedir?", "Mantar", "🍄", "doğa", "7-9", "orta", "Şapkası var, gövdesi kısa"],
    // === 7-9 YAŞ - ZOR ===
    ["Alacakarga bulaca karga, içi dolu kavurga.", "Nar", "🍎", "yiyecek", "7-9", "zor", "Taneleri kırmızı meyve"],
    ["Çalı altında fişek, bunu bilmeyen eşek.", "Tavşan", "🐰", "hayvanlar", "7-9", "zor", "Hızlı koşan hayvan"],
    ["Davdan gelir dak gibi, golları budak gibi.", "Geyik", "🦌", "hayvanlar", "7-9", "zor", "Boynuzlu orman hayvanı"],
    ["Ey milidi milidi, dış kapının kilidi, yatsıdan sonra bize gelen kim idi?", "Uyku", "😴", "doğa", "7-9", "zor", "Gece gelir, gözlerini kapar"],
    ["Dağdan gelir taştan gelir, bir kükremiş aslan gelir.", "Sel", "🌊", "doğa", "7-9", "zor", "Sular dağdan aşağı akar"],
    ["Çalı dibinde mum yanar.", "Çiğdem", "🌸", "doğa", "7-9", "zor", "Baharın müjdecisi çiçek"],
    ["İki dilim ekmek arası, doldurulmuş her bir yanı.", "Sandviç", "🥪", "yiyecek", "7-9", "zor", "Arası dolu ekmek"],
    ["Tepesinde beyaz saç, yeşil elbise, karnı aç.", "Dağ", "🏔️", "doğa", "7-9", "zor", "Zirvesinde kar var"],
    ["Renklerden bir yay, ama onunla ok atılmaz.", "Gökkuşağı", "🌈", "doğa", "7-9", "zor", "Yedi renkli"],
    ["Bozulduğu halde tamir edilmeyen şey.", "Hava", "💨", "doğa", "7-9", "zor", "Hava ... bozuldu denir"],
    // === 10-12 YAŞ - KOLAY ===
    ["Derede tin tin, tepede tin tin, kemiksiz tin tin.", "Yılan", "🐍", "hayvanlar", "10-12", "kolay", "Kemiksiz sürünen"],
    ["İçini boşaltınca büyüyen şey nedir?", "Çukur", "🕳️", "doğa", "10-12", "kolay", "Kazınca derinleşir"],
    ["Her zaman yukarı doğru gider, asla aşağı inmez.", "Yaş", "🎂", "doğa", "10-12", "kolay", "Her yıl bir artar"],
    ["Masaya hangi örtü serilmez?", "Kar örtüsü", "❄️", "doğa", "10-12", "kolay", "Dışarıda her yeri kaplar"],
    ["Sarı mendil mavi denize düşerse ne olur?", "Islanır", "💧", "doğa", "10-12", "kolay", "Suya düşen ne olur?"],
    ["Domates nasıl kızarır?", "Utanınca", "🍅", "yiyecek", "10-12", "kolay", "İnsanlar neden kızarır?"],
    ["En çok kardeşi olan meyve?", "Üzüm", "🍇", "yiyecek", "10-12", "kolay", "Salkımda çok tanesi var"],
    ["Bir küçücük kutudur, bütün dünya yurdudur.", "Radyo", "📻", "eşyalar", "10-12", "kolay", "Ses yayını yapar"],
    ["Adem peygamberin sahip olmadığı ama çocukların sahip olduğu şey?", "Anne-Baba", "👨‍👩‍👧", "doğa", "10-12", "kolay", "İlk insan kimden doğdu?"],
    ["İki sıra asker, birbirine bakışır, arada da düşman dolaşır.", "Diş ve Dil", "🦷", "vücut", "10-12", "kolay", "Ağzında"],
];
