// Batch 2: more riddles for 7-9 and 10-12 age groups
module.exports = [
    // === 10-12 YAŞ - ORTA ===
    ["Gitmesini bilir, gelmesini bilmez.", "Gözyaşı", "😢", "vücut", "10-12", "orta", "Ağlayınca akar"],
    ["Bir kuyu kazdım, suyu çıkmadı; düştüm içine, altı çıkmadı.", "Uyku", "😴", "doğa", "10-12", "orta", "Gece dalarsin"],
    ["Kolsuz, kanatsız duvara çıkar.", "Gölge", "👤", "doğa", "10-12", "orta", "Işık arkanda olunca"],
    ["Üstü yağmur, altı çamur, ortası leziz.", "Sandviç", "🥪", "yiyecek", "10-12", "orta", "İki ekmek arası"],
    ["Beyaz atıma bindim, gittim gittim iz bırakmadım.", "Kayık", "⛵", "araçlar", "10-12", "orta", "Suda gider"],
    ["Herkes onu döver, ama kimse ona acımaz.", "Çivi", "🔨", "eşyalar", "10-12", "orta", "Çekiçle vurulur"],
    ["Ne bir harfi var ne de bir hecesi, ama nice anlamlar taşır.", "Resim", "🖼️", "eşyalar", "10-12", "orta", "Duvara asılır"],
    ["İki kardeş yanyana, birbirini göremez.", "Göz", "👁️", "vücut", "10-12", "orta", "Yüzünde iki tane"],
    ["Sofraya gelir ama yenmez.", "Bıçak", "🔪", "eşyalar", "10-12", "orta", "Keser ama yenmez"],
    ["Gece gelir izinsiz, gündüz kaybolur habersiz.", "Yıldız", "⭐", "doğa", "10-12", "orta", "Gökyüzünde parlar"],
    ["Binlerce elbise giyer, soyulunca ağlatır.", "Soğan", "🧅", "yiyecek", "10-12", "orta", "Katman katman"],
    ["Konuşur ama canlı değil, kapanır ama kutu değil.", "Kitap", "📖", "eşyalar", "10-12", "orta", "Bilgi kaynağı"],
    ["Dili yok ama söyler, kolu yok ama gösterir.", "Saat", "🕐", "eşyalar", "10-12", "orta", "Zamanı bildirir"],
    ["Gider ama adım atmaz, döner ama ayağı yok.", "Tekerlek", "☸️", "eşyalar", "10-12", "orta", "Arabanın altında"],
    ["Elinde tutarsın ama göremezsin.", "Nefes", "💨", "doğa", "10-12", "orta", "Soluk alıp verirsin"],
    ["Bir delikten girer, üç delikten çıkar.", "Gömlek", "👔", "eşyalar", "10-12", "orta", "Giyersin, kolları var"],
    ["Kapıları var ama evi yok, yolcuları var ama ayağı yok.", "Asansör", "🛗", "eşyalar", "10-12", "orta", "Yukarı aşağı gider"],
    ["Her gün doğar ama canlı değil.", "Güneş", "☀️", "doğa", "10-12", "orta", "Sabahları ufukta belirir"],
    ["Yüzü var ama gözü yok, ibresi var ama dikişçi değil.", "Saat", "🕐", "eşyalar", "10-12", "orta", "Duvardan zamanı okursun"],
    ["Kelimeler içinde yaşar, sesler arasında dolaşır.", "Harf", "🔤", "eşyalar", "10-12", "orta", "Alfabede bulunur"],
    // === 10-12 YAŞ - ZOR ===
    ["Bir deniz var geçilmez, bir ağaç var biçilmez, bir çiçek var koparılmaz.", "Gökyüzü-Güneş-Ay", "🌌", "doğa", "10-12", "zor", "Yukarıya bak"],
    ["Yüzer ama gemi değil, soğuk ama buz değil.", "Ördek", "🦆", "hayvanlar", "10-12", "zor", "Gölde yaşar"],
    ["Her sabah dört ayaklı, öğleden sonra iki ayaklı, akşam üç ayaklı.", "İnsan", "🧑", "vücut", "10-12", "zor", "Bebek, genç, yaşlı"],
    ["Söyledikçe kırılır.", "Sır", "🤫", "doğa", "10-12", "zor", "Sessizlik gerektirir"],
    ["Hep koşar ama yerinden ayrılmaz.", "Saat", "🕐", "eşyalar", "10-12", "zor", "Tik tak sesi çıkarır"],
    ["Kim takar herkes bakar, üç gözlü tek ayak.", "Trafik lambası", "🚦", "eşyalar", "10-12", "zor", "Kırmızı sarı yeşil"],
    ["Kanatlarım var uçamam, gözlerim var göremem.", "Ölü balık", "🐟", "hayvanlar", "10-12", "zor", "Cansız deniz canlısı"],
    ["Tutamaz ama taşır, göremez ama bilir.", "Hafıza", "🧠", "vücut", "10-12", "zor", "Beyninde saklarsın"],
    ["Herkes çiğner ama yutmaz.", "Sakız", "🫧", "yiyecek", "10-12", "zor", "Ağızda çiğnenen"],
    ["Atarsın yere düşmez.", "Nara", "🗣️", "doğa", "10-12", "zor", "Bağırarak atarsın"],
    // === EXTRA 4-6 kolay/orta ===
    ["İki eli var, on parmağı, yazı yazar kağıt üstünde.", "Kalem", "✏️", "eşyalar", "4-6", "kolay", "Onunla yazarsın"],
    ["Üstüne binilir, pedal çevilir.", "Bisiklet", "🚲", "araçlar", "4-6", "kolay", "İki tekerlekli araç"],
    ["Geceleyin yanar gündüz söner.", "Yıldız", "⭐", "doğa", "4-6", "kolay", "Gökyüzünde parıldar"],
    ["On tane askercik bir sırada dizilir, onları saymayı hemen herkes bilir.", "Parmak", "🖐️", "vücut", "4-6", "orta", "Ellerinde var"],
    ["Sıcakta erir, soğukta donar.", "Buz", "🧊", "doğa", "4-6", "orta", "Suyu dondurursan olur"],
    ["Her gün gelir kapına ama içeri girmez.", "Gazete", "📰", "eşyalar", "7-9", "orta", "Haberleri okursun"],
    ["Dalgalarla oynar, sahilde bekler.", "Kum", "🏖️", "doğa", "4-6", "kolay", "Deniz kenarında bulunur"],
    ["Yeşildir ama yaprak değil, zıplar ama tavşan değil.", "Kurbağa", "🐸", "hayvanlar", "4-6", "orta", "Vrak vrak der"],
    ["Bacakları çoktur ama yürüyemez.", "Masa", "🪵", "eşyalar", "7-9", "orta", "Dört ayağı var ama yürümez"],
    ["Yağmurda açılır, güneşte kapanır.", "Şemsiye", "☂️", "eşyalar", "4-6", "orta", "Islanmamak için kullanılır"],
    ["Yumuşaktır ama taş gibi batabilir.", "Ekmek", "🍞", "yiyecek", "7-9", "orta", "Bayatlarsa sertleşir"],
    ["Gözü var iğnesi var, dikiş diker durur.", "İğne", "🪡", "eşyalar", "7-9", "zor", "Dikişçi kullanır"],
    ["Bir annem var bin yüzlü, bakınca her seferinde başka gösterir.", "Ayna", "🪞", "eşyalar", "7-9", "orta", "Kim bakarsa onu gösterir"],
    ["Herkes sever onu, ama dişlerimiz ağlar.", "Şeker", "🍬", "yiyecek", "4-6", "orta", "Tatlı ama dişe zararlı"],
    ["Sapı var ama kapı değil, suyu var ama deniz değil.", "Çeşme", "🚰", "eşyalar", "7-9", "orta", "Su içersin ondan"],
    ["İp gibi uzun, dügüm düğüm yol alır.", "Tren", "🚂", "araçlar", "7-9", "kolay", "Vagonları sırayla gider"],
    ["Yere basınca zil çalar.", "Kapı zili", "🔔", "eşyalar", "7-9", "orta", "Evin girişinde"],
    ["Ağzı açık karşıdan bakar, yutmaz ama her şeyi saklar.", "Çekmece", "🗄️", "eşyalar", "10-12", "orta", "Dolabın parçası"],
    ["Toprağın altından çıkar, tarlada büyür, sofraya gelir.", "Patates", "🥔", "yiyecek", "4-6", "kolay", "Kızartıp yersin"],
    ["Kabuğu sert, içi beyaz, hindistandan gelir.", "Hindistancevizi", "🥥", "yiyecek", "10-12", "zor", "Tropik meyve"],
    // === EXTRA 7-9 ve 10-12 ===
    ["Çizgili giyinmiş, ormanda gezer, herkesi korkutur.", "Kaplan", "🐯", "hayvanlar", "7-9", "orta", "Çizgili büyük kedi"],
    ["Boynu uzun, Afrika'da yaşar.", "Zürafa", "🦒", "hayvanlar", "4-6", "kolay", "En uzun boylu hayvan"],
    ["Gagası uzun, balık avlar, bacakları ince.", "Balıkçıl", "🦩", "hayvanlar", "7-9", "zor", "Suda bekleyip avlar"],
    ["Suda yaşar, karada yumurtlar, yavaş gider.", "Kaplumbağa", "🐢", "hayvanlar", "7-9", "orta", "Kabuğunda gizlenir"],
    ["Çölde yaşar, hörgücü var, susuzluğa dayanır.", "Deve", "🐫", "hayvanlar", "7-9", "orta", "Çöl gemisi derler"],
    ["Siyah beyaz giyinmiş, uçamaz ama yüzer.", "Penguen", "🐧", "hayvanlar", "7-9", "orta", "Güney kutbunda yaşar"],
    ["Hortumu var, kulakları büyük, hafızası kuvvetli.", "Fil", "🐘", "hayvanlar", "4-6", "orta", "En büyük kara hayvanı"],
    ["Tırmık tırmık tırmanır, ağaçta fındık arar.", "Sincap", "🐿️", "hayvanlar", "4-6", "orta", "Kuyruklu küçük hayvan"],
    ["Gece avcısı, sesi korkutur, 'hu hu' der.", "Baykuş", "🦉", "hayvanlar", "7-9", "orta", "Gece kuşu"],
    ["Denizin hırsızı, sekiz kolu var.", "Ahtapot", "🐙", "hayvanlar", "7-9", "zor", "Mürekkep püskürtür"],
    ["Yelesi gür, kükreyişi güçlü, ormanların kralı.", "Aslan", "🦁", "hayvanlar", "7-9", "orta", "Ormanların kralı derler"],
    ["Başı taçlı, gagası eğri, gökyüzünün efendisi.", "Kartal", "🦅", "hayvanlar", "10-12", "orta", "En güçlü kuş"],
    ["Tüyleri rengarenk, konuşmayı öğrenir.", "Papağan", "🦜", "hayvanlar", "7-9", "orta", "Konuşan kuş"],
    ["Boynuzları dallanır, ormanda gezer.", "Geyik", "🦌", "hayvanlar", "10-12", "orta", "Boynuzlu zarif hayvan"],
    ["Dikenli postu var, top gibi kıvrılır.", "Kirpi", "🦔", "hayvanlar", "4-6", "kolay", "Küçük dikenli"],
    ["Çok bacaklı, ağ örer, sinek avlar.", "Örümcek", "🕷️", "hayvanlar", "7-9", "zor", "Ağ örer, bekler"],
    ["Işıl ışıl yanar geceleri, küçücük feneri.", "Ateşböceği", "🪲", "hayvanlar", "7-9", "zor", "Gecede parlayan böcek"],
    ["Kanatları tozlu, çiçekleri sever, tırtıldan dönüşür.", "Kelebek", "🦋", "hayvanlar", "4-6", "orta", "Kozadan çıkar"],
    ["Ağacın gövdesini oyar, gagasıyla vurur.", "Ağaçkakan", "🐦", "hayvanlar", "10-12", "orta", "Gagasıyla vurur"],
    ["Toprak altında tünel kazar, gözleri görmez.", "Köstebek", "🐁", "hayvanlar", "10-12", "orta", "Yer altında yaşar"],
    ["Balıkçının sepeti, denizin devi, yüzer balinalar gibi.", "Balina", "🐋", "hayvanlar", "10-12", "orta", "Denizin en büyüğü"],
    ["Su geçirmez kabuğu, kıskaçları güçlü.", "Yengeç", "🦀", "hayvanlar", "10-12", "orta", "Yan yan yürür"],
    // EXTRA yiyecek
    ["Sarı kabuğu soy, tatlı tatlı ye.", "Muz", "🍌", "yiyecek", "4-6", "kolay", "Maymunlar sever"],
    ["Turuncu rengi, beta karoten dolu, tavşanlar sever.", "Havuç", "🥕", "yiyecek", "4-6", "kolay", "Turuncu sebze"],
    ["Yeşil dışı kırmızı içi, yaz ayının serinliği.", "Karpuz", "🍉", "yiyecek", "4-6", "kolay", "Yazın en çok yenen"],
    ["Küçük taneleri, üzüm gibi ama daha küçük.", "Frenk üzümü", "🫐", "yiyecek", "10-12", "zor", "Küçük mavi meyve"],
    ["Portakal renginde, kolay soyulur, dilim dilim yenir.", "Mandalina", "🍊", "yiyecek", "4-6", "kolay", "Küçük portakal gibi"],
    ["Çekirdeksiz yenir, kurusu da güzel.", "Kayısı", "🍑", "yiyecek", "7-9", "kolay", "Turuncu yumuşak meyve"],
    ["Yeşil kabuğu aç, beyaz etini ye, suyunu iç.", "Hindistancevizi", "🥥", "yiyecek", "10-12", "orta", "Tropik meyve"],
    ["Dalında asılı, amber kokulu, sarı renkte.", "Ayva", "🍐", "yiyecek", "10-12", "orta", "Sonbahar meyvesi"],
    ["Ekşisi de var tatlısı da, limonatası yapılır.", "Limon", "🍋", "yiyecek", "7-9", "kolay", "Sarı ekşi meyve"],
    // EXTRA doğa
    ["Geceleri parlar, hep değişir, bazen dolunay.", "Ay", "🌙", "doğa", "4-6", "kolay", "Gökyüzünde gece"],
    ["Dünya döner, o hep sabit kalır.", "Kutup yıldızı", "⭐", "doğa", "10-12", "zor", "Kuzeyi gösterir"],
    ["Sesini duyarsın ama onu göremezsin.", "Rüzgar", "💨", "doğa", "4-6", "orta", "Yaprakları sallar"],
    ["Gökyüzünde çakar, ardından ses gelir.", "Şimşek", "⚡", "doğa", "7-9", "orta", "Fırtınada çakar"],
    ["Yukarıdan aşağı akar, denize ulaşmak ister.", "Şelale", "💦", "doğa", "7-9", "orta", "Su yüksekten düşer"],
    ["Kışın donar, yazın akar, balıklar içinde yaşar.", "Göl", "🏞️", "doğa", "7-9", "kolay", "Durgun su birikintisi"],
    ["Bulutların üstünde, uçaklar arasında, mavilik her yerde.", "Gökyüzü", "🌤️", "doğa", "4-6", "kolay", "Başının üstünde"],
    ["Sabahleyin doğar, akşam kaybolur.", "Güneş", "☀️", "doğa", "4-6", "kolay", "Gündüzün kaynağı"],
    // EXTRA eşyalar  
    ["Sayfaları çevirirsin, harfleri okursun.", "Kitap", "📖", "eşyalar", "4-6", "kolay", "Okuyarak öğrenirsin"],
    ["Düğmelerine basarsın, ekranına bakarsın.", "Bilgisayar", "💻", "eşyalar", "7-9", "kolay", "Teknoloji cihazı"],
    ["İçine binersin, düğmeye basarsın, yukarı çıkarsın.", "Asansör", "🛗", "eşyalar", "7-9", "orta", "Katlara çıkarır"],
    ["Yağmurlu günlerde açılır, güneşli günlerde katlanır.", "Şemsiye", "☂️", "eşyalar", "4-6", "kolay", "Islanmamak için"],
    ["Duvarda asılı, zamanı gösterir.", "Saat", "🕐", "eşyalar", "4-6", "kolay", "Tik tak sesi çıkarır"],
    ["Kağıt üstünde dans eder, renkler bırakır.", "Boya kalemi", "🖍️", "eşyalar", "4-6", "kolay", "Resim yapmak için"],
    // EXTRA VÜCUT
    ["Beş kardeş yan yana, hepsi farklı boyda.", "Parmak", "🖐️", "vücut", "4-6", "kolay", "Ellerinde var"],
    ["Yemek yer, konuşur, güler.", "Ağız", "👄", "vücut", "4-6", "kolay", "Yüzünde"],
    ["Sağa sola çevirir, her yere bakar.", "Boyun", "🦒", "vücut", "7-9", "orta", "Başını tutar"],
    ["Düşünür, hayal kurar, hatırlar.", "Beyin", "🧠", "vücut", "10-12", "orta", "Kafanın içinde"],
];
