// Batch 4: remaining riddles to reach 500 total
module.exports = [
    // GELENEKSEl TARZ BİLMECELER
    ["İnce ince yol gider, suyun üstünde köprü kurar.", "Karınca", "🐜", "hayvanlar", "7-9", "kolay", "Çok çalışkan küçük böcek"],
    ["Ak pak nine, her yeri yine yine.", "Kar", "❄️", "doğa", "7-9", "zor", "Her yeri beyaza boyar"],
    ["Düz ovada bir ağaç, tepesinde yüz yaprak.", "Lahana", "🥬", "yiyecek", "10-12", "zor", "Yaprak yaprak sebze"],
    ["Bir beyaz gelin, dağ başında oturur.", "Kar", "❄️", "doğa", "10-12", "zor", "Dağ zirvesinde beyaz"],
    ["Taştan atarlar ölmez, suya atarlar ölür.", "Ateş", "🔥", "doğa", "10-12", "zor", "Yanar ama suda söner"],
    ["El ele vermiş duvarda durur.", "Tuğla", "🧱", "eşyalar", "10-12", "orta", "Evler bundan yapılır"],
    ["Ak kuşlar dizilir giderler yoldan.", "Dişler", "🦷", "vücut", "7-9", "zor", "Ağzındaki beyazlar"],
    ["Dalda duran toplar, yere düşen koplar.", "Elma", "🍎", "yiyecek", "4-6", "orta", "Kırmızı meyve"],
    ["Bir beyaz nine, kırk dereden su getirir.", "Diş", "🦷", "vücut", "10-12", "zor", "Çiğnemeye yarar"],
    ["Yeşil başlı, kırmızı kuyruklu, yere gömülü.", "Havuç", "🥕", "yiyecek", "4-6", "kolay", "Turuncu sebze"],
    ["İki elle tutulur, ama görünmez.", "Hava", "💨", "doğa", "10-12", "zor", "Soluk alırsın"],
    ["Dışarıda durur, eve girmez ama korur.", "Çit", "🏡", "eşyalar", "7-9", "orta", "Bahçenin etrafında"],
    ["İçinden geçersin ama kesemezsin.", "Rüzgar", "💨", "doğa", "7-9", "orta", "Esiyor"],
    ["Düşer ama kırılmaz, yükselir ama uçmaz.", "Sıcaklık", "🌡️", "doğa", "10-12", "zor", "Termometrede ölçülür"],
    ["Çalar ama müzisyen değil, döver ama kavgacı değil.", "Saat", "🕐", "eşyalar", "10-12", "orta", "Zamanı bildirir"],
    ["Gece uyanır, gündüz uyur, yuvarlak yüzü var.", "Ay", "🌙", "doğa", "4-6", "orta", "Gece gökyüzünde"],
    ["İçinde yaşarsın ama taşıyamazsın.", "Ev", "🏠", "eşyalar", "4-6", "kolay", "Ailenle beraber"],
    ["Tıkla tıkla, harfler çıkar, ekranda yazar.", "Klavye", "⌨️", "eşyalar", "7-9", "kolay", "Bilgisayarın parçası"],
    ["Üstüne basarsan çığlık atar.", "Trompe", "🎺", "eşyalar", "10-12", "zor", "Müzik aleti"],
    ["Sivri uçlu, kağıda dokunur, iz bırakır.", "Kalem", "✏️", "eşyalar", "4-6", "kolay", "Yazı yazarsın"],
    ["Bağırır ama ağzı yok, saati bildirir.", "Çalar saat", "⏰", "eşyalar", "4-6", "orta", "Sabahları uyandırır"],
    ["Tepesi dumanlı, karanlıkta iş görür.", "Baca", "🏭", "eşyalar", "7-9", "zor", "Dumanı çıkarır"],
    ["Yerden göğe uzanır, merdiven merdiven.", "Gökdelen", "🏢", "eşyalar", "10-12", "orta", "Çok katlı bina"],
    ["Dünyayı dolanır ama yerinden kımıldamaz.", "Yol", "🛤️", "doğa", "10-12", "orta", "Araçlar üzerinde gider"],
    ["Bir sepet elma, sayamazsın tanelerini.", "Yıldızlar", "⭐", "doğa", "7-9", "zor", "Gece milyonlarca parlar"],
    ["Boynuna dolar, ısıtır, renkli olur.", "Atkı", "🧣", "eşyalar", "4-6", "kolay", "Kışın giyilir"],
    ["Üstüne oturursan yüzer, altına girersen batarsın.", "Sal", "🛶", "araçlar", "10-12", "orta", "Suda yüzen tahta"],
    ["Sivri tepeleri var, yüksek boylu, yeşil elbiseleri.", "Çam ağacı", "🌲", "doğa", "4-6", "kolay", "Yeni yılda süslenir"],
    ["Yan yana giderler, birbirine benzerler ama farklıdırlar.", "Ray", "🛤️", "araçlar", "10-12", "orta", "Tren bunun üstünde gider"],
    ["Her şeyi bilir ama konuşamaz.", "Ansiklopedi", "📚", "eşyalar", "10-12", "orta", "Bilgi kaynağı"],
    ["Duvara yapışık, dünyada neler olduğunu gösterir.", "Harita", "🗺️", "eşyalar", "10-12", "orta", "Ülkeleri gösterir"],
    ["Bir yüzü aydınlık bir yüzü karanlık, gökyüzünde asılı.", "Ay", "🌓", "doğa", "10-12", "orta", "Evreleri değişir"],
    ["Toparlak göl, etrafı bel, dünyada en tatlı yol.", "Göz yaşı", "😢", "vücut", "10-12", "zor", "Duygulanınca akar"],
    ["İçi sıcak dışı soğuk, bir ucu yanmış.", "Sigara", "🚬", "eşyalar", "10-12", "zor", "Sağlığa zararlı"],
    ["Çiçekler açar kapanır, ay yıldızlar parlar söner.", "Gece gündüz", "🌗", "doğa", "7-9", "orta", "24 saat döngüsü"],
    ["Altın tası, gümüş tası, içinde yağlı pilav.", "Armut", "🍐", "yiyecek", "7-9", "zor", "Yeşilimsi sarı meyve"],
    ["Askere benzer dizilir, büyük küçük sıralanır.", "Diş", "🦷", "vücut", "4-6", "orta", "Ağzında sırayla durur"],
    ["Dalında asılı, çekirdeğini at, kabuğunu ye.", "Ceviz", "🌰", "yiyecek", "7-9", "orta", "Kır ve ye"],
    ["Güneş batınca doğar, güneş doğunca batar.", "Ay", "🌙", "doğa", "7-9", "kolay", "Gece ışığı"],
    ["Tutarsın ama elinde kalmaz, bakarsın ama göremezsin.", "Zaman", "⏳", "doğa", "10-12", "zor", "Geçer gider"],
    ["Bir sofracık, üstü dolu.", "Göl", "🏞️", "doğa", "10-12", "zor", "Durgun su"],
    ["Yaz gelir giyinir, kış gelir soyunur.", "Ağaç", "🌳", "doğa", "7-9", "orta", "Mevsimle değişir"],
    ["Gezip dolanır, bir gün herkesin kapısını çalar.", "Postacı", "📮", "eşyalar", "7-9", "orta", "Mektupları getirir"],
    ["Sırtında evi taşır, nereye giderse orası yurdu.", "Salyangoz", "🐌", "hayvanlar", "4-6", "kolay", "Yavaş hayvan"],
    ["Biri kısa biri uzun, daire çizer ikisi de.", "Saat ibresi", "🕐", "eşyalar", "10-12", "orta", "Saat kadranında döner"],
    ["Bahar müjdecisi, toprağından ilk çıkan.", "Çiğdem", "🌸", "doğa", "10-12", "orta", "İlk bahar çiçeği"],
    ["Yuvarlak karnı, ince boynu, suyu saklı tutar.", "Şişe", "🍾", "eşyalar", "4-6", "kolay", "İçecek koyarsın"],
    ["Dünyayı gezen ama hiç evinden çıkmayan.", "Kaplumbağa", "🐢", "hayvanlar", "10-12", "zor", "Evi sırtında"],
    ["İçi delik, dışı delik, ama su tutar.", "Sünger", "🧽", "eşyalar", "7-9", "zor", "Bulaşık yıkamada kullanılır"],
    ["Gece yanan, gündüz sönen, mumdan farklı.", "Sokak lambası", "🏮", "eşyalar", "7-9", "orta", "Yolları aydınlatır"],
    ["Omuzda taşınır, içinde kitaplar.", "Çanta", "🎒", "eşyalar", "4-6", "kolay", "Okula götürürsün"],
    ["İçine bak kendini gör, duvara as odanı gör.", "Ayna", "🪞", "eşyalar", "4-6", "kolay", "Yansıma gösterir"],
    ["Önden bak arkadan bak, aynısını göreceksin.", "Ayna", "🪞", "eşyalar", "7-9", "kolay", "Simetrik gösterir"],
    ["Rüzgar eser, o döner, elektrik üretir.", "Yel değirmeni", "🌬️", "eşyalar", "10-12", "orta", "Rüzgar enerjisi"],
    ["İki tane var, birbirinden uzak, ama aynı işi yapar.", "Kulak", "👂", "vücut", "4-6", "kolay", "Ses duyarsın"],
    ["Doğada gizlenir, öter, güzel sesi var.", "Bülbül", "🐦", "hayvanlar", "7-9", "orta", "En güzel öten kuş"],
    ["İki dişli, bir gözlü, kumaşı keser.", "Makas", "✂️", "eşyalar", "7-9", "orta", "Terzi kullanır"],
    ["On kişilik sofra, hiç yemek yenilmez.", "Parmaklar", "🖐️", "vücut", "7-9", "zor", "İki elde toplam on"],
    ["Ateşte pişer, herkesin kahvaltısında.", "Ekmek", "🍞", "yiyecek", "4-6", "kolay", "Fırında yapılır"],
    ["Siyah altın denilir, yerden çıkar, enerji verir.", "Petrol", "🛢️", "doğa", "10-12", "zor", "Fosil yakıt"],
    ["Yuvarlak, düz, üstünde ülkeler.", "Dünya", "🌍", "doğa", "7-9", "orta", "Gezegenimiz"],
    ["İçi boş, ağzı geniş, içine su konur.", "Bardak", "🥤", "eşyalar", "4-6", "kolay", "Su içersin onunla"],
    ["Altı tekerlekli, yük taşır.", "Kamyon", "🚚", "araçlar", "4-6", "kolay", "Büyük araç"],
    ["İki katlı, yolcular dolu, şehirde gezer.", "Otobüs", "🚌", "araçlar", "4-6", "kolay", "Toplu taşıma"],
    ["Yolda gider, taksimetre çalışır.", "Taksi", "🚕", "araçlar", "4-6", "kolay", "Sarı araç"],
    ["Sirenleri çalar, yangına koşar.", "İtfaiye", "🚒", "araçlar", "4-6", "kolay", "Kırmızı araç"],
    ["Hastalara yardım eder, sireni çalar.", "Ambulans", "🚑", "araçlar", "4-6", "kolay", "Hastaneye götürür"],
    ["Torpido gibi hızlı, suyun altında gider.", "Denizaltı", "🚢", "araçlar", "10-12", "orta", "Su altı aracı"],
    ["Gökyüzüne fırlatılır, uzaya gider.", "Roket", "🚀", "araçlar", "7-9", "orta", "Astronotları taşır"],
    ["Pervanesi döner, havada asılı kalır.", "Helikopter", "🚁", "araçlar", "7-9", "orta", "Dikey kalkan hava aracı"],
    ["Kadranı var, ibreleri döner, pili var.", "Kol saati", "⌚", "eşyalar", "7-9", "kolay", "Bileğine takarsın"],
    ["Beyaz bir kutu, yiyecekleri soğuk tutar.", "Buzdolabı", "🧊", "eşyalar", "4-6", "kolay", "Mutfakta durur"],
    ["İçine koyarsın, düğmesine basarsın, ısınır.", "Mikrodalga", "📦", "eşyalar", "7-9", "kolay", "Hızlı ısıtır"],
    ["Kirliler girer, temizler çıkar, makine döner.", "Çamaşır makinesi", "🧺", "eşyalar", "7-9", "kolay", "Giysileri yıkar"],
    ["Kıvırcık, yeşil, salataya konur.", "Marul", "🥬", "yiyecek", "4-6", "kolay", "Salata yaprağı"],
    ["Mor kabuğu, beyaz içi, yağda kızartılır.", "Patlıcan", "🍆", "yiyecek", "4-6", "kolay", "Mor sebze"],
    ["Sarı taneli, koçanında büyür.", "Mısır", "🌽", "yiyecek", "4-6", "kolay", "Patlatılınca patlamış olur"],
    ["Sert kabuğu, tatlı içi, kurusu da güzel.", "Fındık", "🌰", "yiyecek", "7-9", "kolay", "Kabuklu kuruyemiş"],
    ["Uzun, turuncu, toprağın altında büyür.", "Havuç", "🥕", "yiyecek", "4-6", "kolay", "Tavşanın sevdiği"],
    ["Kış meyvesi, C vitamini deposu.", "Portakal", "🍊", "yiyecek", "4-6", "kolay", "Turuncu meyve"],
    ["Yuvarlak, kırmızı, çekirdekli, ağaçta yetişir.", "Vişne", "🍒", "yiyecek", "7-9", "orta", "Ekşimsi kırmızı meyve"],
    ["Kabuğunu soy, dilimle, ekşi de olabilir tatlı da.", "Portakal", "🍊", "yiyecek", "4-6", "kolay", "Sıkılınca meyvesuyu olur"],
    ["Yazın yetişir, kırmızı pullu, ateş gibi.", "Çilek", "🍓", "yiyecek", "4-6", "kolay", "Küçücük kırmızı"],
];
