// Batch 5: ~100 riddles to bring us to 500 total
module.exports = [
    // === 10-12 KOLAY/ORTA — filling biggest gap ===
    ["Harflerden oluşur, cümleler kurar, okunur.", "Kelime", "🔤", "eşyalar", "10-12", "kolay", "Dilde kullanılır"],
    ["Meyvelerin kraliçesi, tropik ülkelerin hediyesi.", "Ananas", "🍍", "yiyecek", "10-12", "kolay", "Dikenleri olan meyve"],
    ["Onu herkes yer ama kimse görmez.", "Hava", "💨", "doğa", "10-12", "kolay", "Solursun"],
    ["İçinde yolcular, gökyüzünde yol alır.", "Uçak", "✈️", "araçlar", "10-12", "kolay", "Göklerin aracı"],
    ["Yüzlerce sayfası, hikayeleri var, rafta durur.", "Roman", "📚", "eşyalar", "10-12", "kolay", "Edebiyat eseri"],
    ["Sayılarla dolu, problemler çözersin.", "Matematik", "🔢", "eşyalar", "10-12", "kolay", "Okul dersi"],
    ["Gezegenimiz, mavimsi, suyun bolluğu.", "Dünya", "🌍", "doğa", "10-12", "kolay", "Üzerinde yaşıyoruz"],
    ["Halkalı gezegen, güneş sisteminde.", "Satürn", "🪐", "doğa", "10-12", "orta", "Halkaları var"],
    ["Kırmızı gezegen, komşumuz.", "Mars", "🔴", "doğa", "10-12", "orta", "Kırmızı yüzeyli"],
    ["Güneşe en yakın, çok sıcak.", "Merkür", "🌑", "doğa", "10-12", "orta", "İlk gezegen"],
    ["Geceleyin ses çıkarır, ağustosun böceği.", "Ağustos böceği", "🦗", "hayvanlar", "10-12", "kolay", "Yazın öter"],
    ["Yüzmeyi bilir, suda ve karada yaşar.", "Kurbağa", "🐸", "hayvanlar", "10-12", "kolay", "Amfibi"],
    ["Altı bacaklı, yazın uğuldayan.", "Sinek", "🪰", "hayvanlar", "10-12", "kolay", "Vızıldayan böcek"],
    ["Çiçekten çiçeğe konar, tozlaşma yapar.", "Arı", "🐝", "hayvanlar", "10-12", "kolay", "Polinasyonu sağlar"],
    ["Gece avlanır, tüyleri yumuşak, sesi ürpertici.", "Baykuş", "🦉", "hayvanlar", "10-12", "kolay", "Gece kuşu"],
    ["Derisi benekli, Afrika'nın hızlı avcısı.", "Çita", "🐆", "hayvanlar", "10-12", "orta", "En hızlı kara hayvanı"],
    ["Sürüde yaşar, otlarla beslenir, Afrika'da.", "Antilop", "🦌", "hayvanlar", "10-12", "orta", "Boynuzlu otçul"],
    ["Kanatlı ama uçamaz, koşusu hızlı, boynu uzun.", "Devekuşu", "🦃", "hayvanlar", "10-12", "orta", "En büyük kuş"],
    ["Değirmende öğütülür, hamur olur, ekmek pişer.", "Un", "🌾", "yiyecek", "10-12", "orta", "Buğdaydan yapılır"],
    ["Toprakta yetişir, kazılarak çıkarılır, tatlıdır.", "Şeker pancarı", "🌱", "yiyecek", "10-12", "zor", "Şeker bundan üretilir"],
    ["Denizden çıkar, beyazdır, yemeğe tat katar.", "Tuz", "🧂", "yiyecek", "10-12", "kolay", "Her yemeğe konur"],
    ["İnce uzun, suda pişer, sosla yenir.", "Makarna", "🍝", "yiyecek", "10-12", "kolay", "İtalyan yemeği favorisi"],
    ["Hamurdan yapılır, üstü soslü, peynirli.", "Lahmacun", "🫓", "yiyecek", "10-12", "kolay", "Türk fast food"],
    ["İnce hamur, et ve sebze sarılır.", "Dürüm", "🌯", "yiyecek", "10-12", "kolay", "Sadece sararsın"],
    ["Yoğurttan yapılır, yaz içeceği.", "Ayran", "🥛", "yiyecek", "10-12", "kolay", "Türklerin içeceği"],
    ["Ağzında eritirsin, kakaolu tatlı.", "Çikolata", "🍫", "yiyecek", "7-9", "kolay", "Kahverengi tatlı"],
    ["Soğuk soğuk, meyveli, bardakta.", "Meyvesuyu", "🧃", "yiyecek", "4-6", "kolay", "Meyveden sıkılır"],
    // === 7-9 ZOR — en düşük grup ===
    ["Bir orda bir burda, ama asla ikisi bir arada.", "Dün ve yarın", "📅", "doğa", "7-9", "zor", "Zaman kavramı"],
    ["Herkes taşır ama kimse görmez.", "İsim", "🏷️", "doğa", "7-9", "zor", "Doğduğunda verilir"],
    ["Yüzü var gülmez, sırtı var eğilmez.", "Yastık", "🛏️", "eşyalar", "7-9", "zor", "Başını koyarsın"],
    ["Sabahları kalkınca ilk gördüğün.", "Tavan", "🏠", "eşyalar", "7-9", "zor", "Odanın üst kısmı"],
    ["Denizden çıkar, buluta gider, yağmur olur.", "Buharlaşma", "💨", "doğa", "7-9", "zor", "Su döngüsü"],
    ["Yemyeşil ama yenmez, üstüne basarsın.", "Çim", "🌿", "doğa", "7-9", "zor", "Bahçede büyür"],
    ["Yapraklar döker, ağaçlar çıplak kalır.", "Sonbahar", "🍂", "doğa", "7-9", "zor", "Yaprak döken mevsim"],
    ["Düğmesine bas, ışık gelsin.", "Elektrik düğmesi", "💡", "eşyalar", "7-9", "zor", "Duvardaki küçük şey"],
    ["İpi çek, ses gelsin.", "Zil", "🔔", "eşyalar", "7-9", "zor", "Ding dong"],
    ["İçi dolu ama göremezsin, kulaklarınla duyarsın.", "Müzik", "🎵", "eşyalar", "7-9", "zor", "Kulağa hoş gelir"],
    ["Onunla uçamazsın ama hayal kurarsın.", "Kitap", "📖", "eşyalar", "7-9", "zor", "Okuyarak dünyaları gezersin"],
    // === 4-6 ZOR — en az olan ===
    ["Altı beyaz üstü yeşil, taştan sert pamuktan yumuşak.", "Turp", "🌱", "yiyecek", "4-6", "zor", "Topraktan çıkan sebze"],
    ["Bir kuyu kazdım altta kaydım.", "Çorap", "🧦", "eşyalar", "4-6", "zor", "Ayağına giyersin"],
    ["Düz gider, eğri gelir.", "Bumerang", "🪃", "eşyalar", "4-6", "zor", "Atınca geri döner"],
    ["Hem gider hem gelir, ama yerinden ayrılmaz.", "Kapı", "🚪", "eşyalar", "4-6", "zor", "Açılıp kapanır"],
    ["Başı var kuyruğu yok, para ile ilgili.", "Tura", "🪙", "eşyalar", "4-6", "zor", "Yazı tura atarsın"],
    ["Gökyüzünde uçar, beyazdır, şekil değiştirir.", "Bulut", "☁️", "doğa", "4-6", "zor", "Yağmur ondan yağar"],
    ["Gece parlar ama elde tutamazsın.", "Yıldız", "⭐", "doğa", "4-6", "zor", "Milyonlarca var"],
    ["Duvarda durur, çerçevesi var, anıları saklar.", "Fotoğraf", "🖼️", "eşyalar", "4-6", "zor", "Hatıra"],
    // === EXTRA — balanced fill ===
    ["Suyun içinde yaşar, kabukları inci saklar.", "Midye", "🦪", "hayvanlar", "10-12", "zor", "Deniz canlısı"],
    ["Dikenli çölde yaşar, suyu kendi içinde saklar.", "Kaktüs", "🌵", "doğa", "10-12", "orta", "Çöl bitkisi"],
    ["Elektriklenir, saçları diken diken eder.", "Statik", "⚡", "doğa", "10-12", "zor", "Sürtünme ile olur"],
    ["Havuza dalarsın, kulaç atarsın.", "Yüzme", "🏊", "eşyalar", "7-9", "kolay", "Su sporu"],
    ["Basketbol potasına atılır.", "Top", "🏀", "eşyalar", "7-9", "kolay", "Turuncu top"],
    ["Sahadaki oyuncular, gol atarlar.", "Futbol", "⚽", "eşyalar", "7-9", "kolay", "Dünya'nın en sevilen sporu"],
    ["Her yemekte sofranın başında.", "Tabak", "🍽️", "eşyalar", "4-6", "kolay", "Yemek koyarsın"],
    ["Çatal, kaşık, bıçak üçlüsünün yeri.", "Çekmece", "🗄️", "eşyalar", "7-9", "orta", "Mutfakta durur"],
    ["Yazın sıcağında seni serinletir, tavandan döner.", "Vantilatör", "🌀", "eşyalar", "7-9", "orta", "Pervaneli cihaz"],
    ["Karda kayarsın, iki tahta ayağında.", "Kayak", "⛷️", "eşyalar", "10-12", "kolay", "Kış sporu"],
    ["Buzda kayarsın, ayağında bıçak.", "Buz pateni", "⛸️", "eşyalar", "10-12", "kolay", "Buz pisti sporu"],
    ["Atarsın havaya, geri gelir yere.", "Top", "🏐", "eşyalar", "4-6", "kolay", "Yuvarlak oyuncak"],
    ["Duvara yapışır, saati gösterir.", "Duvar saati", "🕐", "eşyalar", "4-6", "kolay", "Zamanı söyler"],
    ["Uzun tünel, içinden tren geçer.", "Metro", "🚇", "araçlar", "10-12", "kolay", "Yeraltı treni"],
    ["İki teker, motor gürler, kasklı binersin.", "Motosiklet", "🏍️", "araçlar", "7-9", "orta", "Motorlu iki tekerlekli"],
    ["Yağmurda giyersin, seni ıslatmaz.", "Yağmurluk", "🧥", "eşyalar", "4-6", "kolay", "Su geçirmez giysi"],
    ["Geceleyin yol gösterir, etrafı aydınlatır.", "Fener", "🏮", "eşyalar", "4-6", "kolay", "Taşınabilir ışık"],
    ["Sabahın ilk ışığı, ufukta beliren.", "Şafak", "🌅", "doğa", "10-12", "orta", "Güneş doğmadan önce"],
    ["Akşamın son ışığı, gökyüzü kızarır.", "Gün batımı", "🌇", "doğa", "7-9", "orta", "Güneş batarken"],
    ["İçinden tren geçer, her iki yanı dik.", "Vadi", "🏞️", "doğa", "10-12", "orta", "İki dağ arası"],
    ["Tropikal, sıcak, palmiyeli.", "Ada", "🏝️", "doğa", "10-12", "orta", "Denizle çevrili kara"],
    ["Uzay boşluğunda döner, güneşin etrafında.", "Gezegen", "🪐", "doğa", "10-12", "orta", "Yörüngede döner"],
    ["Yılda bir gelir, pastası olur, mumları sönersin.", "Doğum günü", "🎂", "doğa", "4-6", "kolay", "Yaşın bir artar"],
    ["Okulda çalar, ders biter.", "Zil", "🔔", "eşyalar", "4-6", "kolay", "Teneffüs başlar"],
    ["İğnesi sarar, ipliği geçer, kumaş birleşir.", "Dikiş makinesi", "🧵", "eşyalar", "10-12", "orta", "Terzi kullanır"],
    ["Kış sabahları camda oluşur, güneş eritir.", "Buz çiçeği", "❄️", "doğa", "7-9", "orta", "Camda desen oluşur"],
    ["Yaprakları düşer, dalları kalır, baharda yeniden doğar.", "Ağaç", "🌳", "doğa", "7-9", "kolay", "Mevsimlerle değişir"],
    ["Tahta üstünde oynanır, siyah ve beyaz taşları var.", "Satranç", "♟️", "eşyalar", "10-12", "orta", "Strateji oyunu"],
    ["Topraktan yapılır, ateşte pişer, su tutar.", "Çömlek", "🏺", "eşyalar", "10-12", "orta", "Seramik kap"],
    ["Boyamak için kullanılır, tüpten çıkar.", "Boya", "🎨", "eşyalar", "4-6", "kolay", "Resim yaparken kullanırsın"],
    ["Tepesinde yıldız, yılbaşında süslenir.", "Çam ağacı", "🎄", "doğa", "4-6", "kolay", "Yılbaşı ağacı"],
    ["Zıpla zıpla, ipten atla.", "İp atlama", "🤸", "eşyalar", "4-6", "kolay", "Oyun parkında yapılır"],
    ["Çamurdan şekil yapar, fırında pişirirsin.", "Seramik", "🏺", "eşyalar", "10-12", "orta", "El sanatı"],
    ["Sivri ucu, düz sırtı, keser biçer.", "Balta", "🪓", "eşyalar", "10-12", "orta", "Odun kesersin"],
    ["Kumdan yapılır, dalgalar yıkar.", "Kum kalesi", "🏰", "eşyalar", "4-6", "kolay", "Sahilde yaparsın"],
    ["Rüzgar eser, yapraklar uçar, sonbahar gelir.", "Eylül", "🍂", "doğa", "7-9", "orta", "Okulun başladığı ay"],
    ["Çan çalar, öğrenciler koşar.", "Okul zili", "🔔", "eşyalar", "4-6", "kolay", "Ders başladı"],
    ["İçi pamuk, dışı kumaş, başını koyarsın.", "Yastık", "🛏️", "eşyalar", "4-6", "kolay", "Uyurken altına koyarsın"],
    ["Tabağında durur, çatalınla yersin, anne yapar.", "Yemek", "🍽️", "yiyecek", "4-6", "kolay", "Karnını doyurur"],
    ["Küçük bir sandık, müzik çalar.", "Müzik kutusu", "🎶", "eşyalar", "7-9", "orta", "Kapağını açınca çalar"],
    ["Altından ateş yanar, üstünde yemek pişer.", "Ocak", "🔥", "eşyalar", "7-9", "kolay", "Mutfakta pişirirsin"],
    ["İnce dalda sallanır, rüzgarda dans eder.", "Yaprak", "🍃", "doğa", "4-6", "kolay", "Ağaçta yeşil"],
    ["Kırmızı gövde, yeşil baş, acıdır.", "Turp", "🌶️", "yiyecek", "7-9", "kolay", "Kök sebze"],
    ["Kare kare dizilir, siyah beyaz, zeka ister.", "Bulmaca", "🧩", "eşyalar", "10-12", "kolay", "Çözmek eğlencelidir"],
    ["Yumurtadan çıkar, civciv olur, büyür.", "Tavuk", "🐔", "hayvanlar", "4-6", "kolay", "Civildayan yavru"],
    ["Dört mevsim yeşil, sivri yaprakları.", "Servi", "🌲", "doğa", "10-12", "orta", "İnce uzun ağaç"],
    ["Minik kanatları var, bal toplar, çiçek sever.", "Kelebek", "🦋", "hayvanlar", "4-6", "kolay", "Rengârenk kanatlar"],
    ["Kışı uyuyarak geçirir, yazın ormanı dolaşır.", "Ayı", "🐻", "hayvanlar", "7-9", "orta", "Kış uykusuna yatan"],
    ["İki gözü parlak, dört tekerleği var, yolda gider.", "Araba", "🚗", "araçlar", "4-6", "kolay", "Farları yanar"],
];
