// Batch 3: more riddles to fill gaps and reach 500 total
module.exports = [
    // === EXTRA HAYVANLAR - tüm yaş grupları ===
    ["Gökyüzünde süzülür, fare avlar, sesi keskin.", "Şahin", "🦅", "hayvanlar", "10-12", "orta", "Avlayan kuş"],
    ["Sahilde dolaşır, kabuğunu taşır, denizi sever.", "Yengeç", "🦀", "hayvanlar", "7-9", "kolay", "Yan yürüyen"],
    ["Uzun dili var, sinekleri yakalar, renk değiştirir.", "Bukalemun", "🦎", "hayvanlar", "10-12", "zor", "Renk değiştiren sürüngen"],
    ["İpek örer, kozasında yaşar, kelebek olur.", "İpekböceği", "🐛", "hayvanlar", "10-12", "zor", "Dut yaprağı yer"],
    ["Gece gözü parlar, sessizce avlanır, pençeleri keskin.", "Kedi", "🐱", "hayvanlar", "7-9", "orta", "Evdeki avcı"],
    ["Daldan dala zıplar, muz sever, komik hareketler yapar.", "Maymun", "🐒", "hayvanlar", "4-6", "kolay", "Ağaçlarda yaşayan hayvan"],
    ["Çizgileri siyah beyaz, ata benzer ama değil.", "Zebra", "🦓", "hayvanlar", "4-6", "orta", "Çizgili at"],
    ["Suya dalar, balık tutar, tüyleri su geçirmez.", "Pelikan", "🦤", "hayvanlar", "10-12", "orta", "Gagasında torba var"],
    ["Uzun başparmaklı, ağaçlarda uyur, gece avcısı.", "Baykuş", "🦉", "hayvanlar", "7-9", "kolay", "Gece gözleri parlayan kuş"],
    ["Gagasıyla odun deler, kırmızı tepeli.", "Ağaçkakan", "🐦", "hayvanlar", "7-9", "orta", "Ağacı tıkır tıkır vurur"],
    ["Sürüde gezer, yünü sıcak tutar, meleşir.", "Koyun", "🐑", "hayvanlar", "4-6", "kolay", "Yün veren hayvan"],
    ["Suyu fışkırtır, denizde yaşar, çok zeki.", "Yunus", "🐬", "hayvanlar", "7-9", "orta", "Denizin akıllı canlısı"],
    ["Kanatları rengarenk, çiçeklere konar, nektarı sever.", "Sinek kuşu", "🐦", "hayvanlar", "10-12", "zor", "En küçük kuş"],
    ["Uzun bacaklı, bataklıkta yaşar, tek ayak üstünde durur.", "Flamingo", "🦩", "hayvanlar", "7-9", "zor", "Pembe kuş"],
    ["Derisi pullu, suda ve karada yaşar, soğukkanlı.", "Timsah", "🐊", "hayvanlar", "10-12", "orta", "Büyük sürüngen"],
    ["Ormanda ulur, sürüde avlanır, köpeğe benzer.", "Kurt", "🐺", "hayvanlar", "10-12", "orta", "Uluyarak iletişim kurar"],
    // === EXTRA YİYECEK ===
    ["Tarlada yetişir, öğütülür, ekmek olur.", "Buğday", "🌾", "yiyecek", "7-9", "orta", "Ekmek bundan yapılır"],
    ["Dalında olgunlaşır, reçel yapılır, tatlıdır.", "İncir", "🫐", "yiyecek", "7-9", "orta", "Yumuşak tatlı meyve"],
    ["Sivri burnu var, acısı yakıcı, yemeklere tat katar.", "Biber", "🌶️", "yiyecek", "7-9", "orta", "Acı yapan sebze"],
    ["Toprak altında büyür, kızartılır, püresi yapılır.", "Patates", "🥔", "yiyecek", "4-6", "kolay", "Cips bundan yapılır"],
    ["Beyaz tanecikler, her yemeğin yanında.", "Pirinç", "🍚", "yiyecek", "7-9", "orta", "Pilavın hammaddesi"],
    ["Budaklardan süzülür, arılar toplar, tatlıdır.", "Bal", "🍯", "yiyecek", "4-6", "orta", "Arıların yaptığı tatlı"],
    ["Kabuklu, çatlağından güler, kışın yenir.", "Fıstık", "🥜", "yiyecek", "7-9", "orta", "Kabuklu yemiş"],
    ["Uzun ince, İtalya'dan gelir, makarna ile yenir.", "Spagetti", "🍝", "yiyecek", "7-9", "kolay", "İtalyan makarnası"],
    ["Sıcak sıcak fırından çıkar, peynirli ya da etli.", "Pide", "🫓", "yiyecek", "7-9", "kolay", "Ramazanda yenir"],
    ["Yuvarlak, üstü soslu, peynirli, dilim dilim kesilir.", "Pizza", "🍕", "yiyecek", "4-6", "kolay", "İtalyan yemeği"],
    ["Çayın yanında, şekerli, fırında yapılır.", "Kurabiye", "🍪", "yiyecek", "4-6", "kolay", "Tatlı hamur işi"],
    ["Sıcak suda demlenir, bardağa dökülür, yanına şeker.", "Çay", "🍵", "yiyecek", "4-6", "kolay", "Türklerin ulusal içeceği"],
    ["İnekten gelir, beyazdır, kemikleri güçlendirir.", "Süt", "🥛", "yiyecek", "4-6", "kolay", "Beyaz içecek"],
    ["Soğuk soğuk yenir, yaz günlerinin vazgeçilmezi, çeşit çeşit.", "Dondurma", "🍦", "yiyecek", "4-6", "kolay", "Yazın yenir"],
    // === EXTRA DOĞA ===
    ["Rüzgar eser, gökyüzünde uçar, kuyruklu.", "Uçurtma", "🪁", "eşyalar", "4-6", "kolay", "İple tutarsın, havada süzülür"],
    ["Kışın yaprağını döker, yazın gölge verir.", "Ağaç", "🌳", "doğa", "4-6", "kolay", "Parka gidince altında oturursun"],
    ["Geceleri dans eder gökyüzünde, kutuplarda görülür.", "Kuzey ışıkları", "🌌", "doğa", "10-12", "zor", "Kutuplardaki ışık gösterisi"],
    ["Toprağın derinlerinde saklı, milyonlarca yıllık.", "Fosil", "🦴", "doğa", "10-12", "zor", "Dinozor kalıntısı"],
    ["Yanardağdan çıkar, kırmızı akar, her şeyi yakar.", "Lav", "🌋", "doğa", "10-12", "orta", "Volkan patlamasında çıkar"],
    ["Damla damla birikir, dere olur, denize kavuşur.", "Su", "💧", "doğa", "4-6", "kolay", "Hayatın kaynağı"],
    ["Topraktan çıkar, gökyüzüne uzanır, meyve verir.", "Ağaç", "🌳", "doğa", "4-6", "kolay", "Kuşların evi"],
    ["Tuzlu mu tuzlu, dibi derin, balıklar yüzer içinde.", "Deniz", "🌊", "doğa", "4-6", "kolay", "Tatilde yüzersin"],
    ["Çok yüksek, tepesi karlı, tırmanılır.", "Dağ", "🏔️", "doğa", "4-6", "kolay", "Tepe tepe yükselen"],
    ["Sabahları çiçeklerde parlar, güneçle kaybolur.", "Çiy", "💧", "doğa", "10-12", "orta", "Sabah damlacıkları"],
    ["Kabuğu sert, kırılınca içinden lezzet çıkar.", "Ceviz", "🌰", "yiyecek", "7-9", "kolay", "Sert kabuklu yemiş"],
    ["Ovada akar, şehirler kenarında, balıklar yüzer.", "Nehir", "🏞️", "doğa", "7-9", "kolay", "Şehirlere hayat verir"],
    ["İlkbaharda açar, arıları çeker, güzel kokar.", "Çiçek", "🌸", "doğa", "4-6", "kolay", "Bahçeleri süsler"],
    // === EXTRA EŞYALAR ===
    ["Tekerleği var, direksiyonu var, yolda gider.", "Araba", "🚗", "araçlar", "4-6", "kolay", "Yolda gider"],
    ["Ayağına giyersin, bağcıklıdır, yürüyüşe çıkarsın.", "Ayakkabı", "👟", "eşyalar", "4-6", "kolay", "Ayağına giyersin"],
    ["Akıllıdır, ekranı var, cebinde taşırsın.", "Telefon", "📱", "eşyalar", "7-9", "kolay", "Arama yaparsın"],
    ["İçine oturursun, sallanırsın, bahçede durur.", "Salıncak", "🎠", "eşyalar", "4-6", "kolay", "Parkta sallanırsın"],
    ["Havada uçar, motoru gürler, yolcular taşır.", "Uçak", "✈️", "araçlar", "4-6", "kolay", "Gökyüzünde gider"],
    ["Anahtarla açılır, içinde eşyalar durur.", "Dolap", "🗄️", "eşyalar", "4-6", "kolay", "Kıyafetlerini koyarsın"],
    ["Suda yüzer, yelkeni var, rüzgarla gider.", "Yelkenli", "⛵", "araçlar", "7-9", "orta", "Denizde gider"],
    ["Başına takarsın, güneşten korur.", "Şapka", "🎩", "eşyalar", "4-6", "kolay", "Başlık"],
    ["Burnuna takarsın, uzağı yakın eder.", "Gözlük", "👓", "eşyalar", "4-6", "kolay", "Görmeni kolaylaştırır"],
    ["Kışın giyersin, sıcak tutar, pofuduk.", "Mont", "🧥", "eşyalar", "4-6", "kolay", "Kışlık giysi"],
    ["İpe asarsın, güneşte kurur.", "Çamaşır", "👕", "eşyalar", "4-6", "kolay", "Yıkadıktan sonra kurutursun"],
    ["Rüzgarı keser, kapıda durur, cam da olabilir.", "Pencere", "🪟", "eşyalar", "7-9", "kolay", "Dışarıyı ondan izlersin"],
    ["Kağıdı keser, kumaşı biçer, iki ağızlı.", "Makas", "✂️", "eşyalar", "4-6", "kolay", "Kesmek için kullanılır"],
    ["Üstüne uzanırsın, geceleri uyursun.", "Yatak", "🛏️", "eşyalar", "4-6", "kolay", "Uyumak için"],
    ["Duvara çakar, resim asarsın.", "Çivi", "📌", "eşyalar", "7-9", "orta", "Çekiçle vurulur"],
    // DAHA ÇOK BİLMECE - geleneksel tarz
    ["İçi boş dışı dolu, vurulunca ses verir.", "Davul", "🥁", "eşyalar", "4-6", "orta", "Bayramda çalınır"],
    ["Dağda otlar, evde halı olur.", "Koyun", "🐑", "hayvanlar", "7-9", "orta", "Yünü halı olur"],
    ["Toprağa düşer, dallanır budaklanır.", "Tohum", "🌱", "doğa", "7-9", "orta", "Bitkinin başlangıcı"],
    ["Pencerede durur, ışık verir, dışarıyı gösterir.", "Cam", "🪟", "eşyalar", "7-9", "kolay", "Saydam, kırılgan"],
    ["Üç bacağı var, resim çizilir üstünde.", "Sehpa", "🎨", "eşyalar", "10-12", "orta", "Ressam kullanır"],
    ["Yuvarlak arkadaş, pedalı çevir, git.", "Bisiklet", "🚲", "araçlar", "4-6", "kolay", "İki tekerlekli"],
    ["Kağıttan yapılır, uçar ama kuş değil.", "Uçak (kağıt)", "✈️", "eşyalar", "4-6", "kolay", "Katlayıp atarsın"],
    ["Her kapıda asılı, çevirirsen açılır.", "Anahtar", "🔑", "eşyalar", "4-6", "kolay", "Kilidi açar"],
    ["İnce ince teller, müzik sesleri çıkar.", "Gitar", "🎸", "eşyalar", "7-9", "orta", "Telli çalgı"],
    ["Yuvarlak, ortası delik, parmağa geçer.", "Yüzük", "💍", "eşyalar", "7-9", "kolay", "Parmağa takılan süs"],
    ["Denizde gider, düdüğü öter, kocaman.", "Gemi", "🚢", "araçlar", "4-6", "kolay", "Büyük deniz aracı"],
    ["İçi sıcak, dışı soğuk, yemek pişer.", "Fırın", "🏠", "eşyalar", "7-9", "orta", "Ekmek pişirilen yer"],
    ["Karanlıkta yolunu aydınlatır, elde taşınır.", "El feneri", "🔦", "eşyalar", "7-9", "kolay", "Karanlıkta ışık tutar"],
    ["Tıp tıp yağar, şemsiye açılır.", "Yağmur", "🌧️", "doğa", "4-6", "kolay", "Buluttan düşer"],
    ["Küçücük ev, arılar yapar, bal dolu.", "Petek", "🐝", "doğa", "7-9", "orta", "Arının evi"],
    ["Gökyüzünün mavisi, denizin derinliği.", "Mavi", "🔵", "doğa", "10-12", "orta", "Bir renk"],
    ["Dört mevsim var, hangisinde yapraklar düşer?", "Sonbahar", "🍂", "doğa", "4-6", "kolay", "Yaprak döken mevsim"],
    ["Dört mevsim var, hangisinde çiçekler açar?", "İlkbahar", "🌷", "doğa", "4-6", "kolay", "Çiçeklerin açtığı mevsim"],
    ["Dört mevsim var, hangisinde kar yağar?", "Kış", "❄️", "doğa", "4-6", "kolay", "En soğuk mevsim"],
    ["Dört mevsim var, hangisinde denize girilir?", "Yaz", "☀️", "doğa", "4-6", "kolay", "En sıcak mevsim"],
    ["Yer çeker ama eli yok, düşürür ama itme yok.", "Yerçekimi", "🌍", "doğa", "10-12", "zor", "Newton keşfetti"],
    ["Renklerin anası, hepsini içinde barındırır.", "Beyaz", "⬜", "doğa", "10-12", "zor", "Işık bu renkte"],
    ["Ne su ne ateş, ama ikisini de söndürür.", "Toprak", "🌍", "doğa", "10-12", "zor", "Bitkiler ondan beslenir"],
    ["Sessiz sedasız gelir, dünyayı beyaza boyar.", "Kar", "❄️", "doğa", "4-6", "orta", "Kışın yağar"],
    ["Dalga dalga saçları, rüzgarda savrulan.", "Saç", "💇", "vücut", "7-9", "orta", "Başının üstünde"],
    ["Otuz iki asker sıra sıra dizilir.", "Diş", "🦷", "vücut", "7-9", "kolay", "Yemek yerken kullanırsın"],
    ["İki küçük kuyu, birbirinin aynısı.", "Burun delikleri", "👃", "vücut", "7-9", "orta", "Nefes alırsın"],
    ["Görmeden duyar, duymadan hisseder.", "Kalp", "❤️", "vücut", "10-12", "orta", "Göğsünde atar"],
    ["Açılır kapanır, seni korur, dışarıyı gösterir.", "Göz kapağı", "👁️", "vücut", "10-12", "orta", "Gözünü korur"],
    ["Her gün uzar ama canlı değildir.", "Tırnak", "💅", "vücut", "7-9", "orta", "Parmaklarında büyür"],
    ["Dokuz aylık misafir, dünyaya gelince ağlar.", "Bebek", "👶", "vücut", "7-9", "zor", "Yeni doğan"],
    ["Bizi ayakta tutar, otuz üç tanedir.", "Omurga", "🦴", "vücut", "10-12", "zor", "Sırtında"],
    ["Suyu filtreler, vücudun temizlikçisi.", "Böbrek", "🫘", "vücut", "10-12", "zor", "İç organ"],
    ["Akciğerlerin işi, nefes al nefes ver.", "Solunum", "💨", "vücut", "10-12", "orta", "Yaşamak için yaparsın"],
    ["Kanı pompalar, durmadan çalışır.", "Kalp", "❤️", "vücut", "10-12", "orta", "Göğsünde"],
];
